version: '3.2'

services:

    # api:
    #     build: ./api
    #     depends_on:
    #         - db
    #         - cache
    #     env_file: .env.local
    #     environment:
    #         - DJANGO_SETTINGS_MODULE=settings
    #     volumes:
    #         - api_uwsgispooler_dev:/var/uwsgispooler
    #         - api_uwsgilog_dev:/var/log/uwsgi/
    #         - ./api:/app:cached
    #     ports:
    #         - 8081:8000
    #     command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

    apiv3:
        build:
            context: ./apiv3
            dockerfile: docker/local/Dockerfile
        depends_on:
            - db
            - cache
        env_file: .env.local
        volumes:
            - ./apiv3:/app:cached
        ports:
            - 8082:8000
        command: ["/start.sh"]

    # web-buscador:
    #     image: cypress/base:10
    #     ports:
    #         - 8083:8080
    #     command: bash -c "yarn && yarn serve"
    #     working_dir: /src
    #     volumes:
    #         - ./web-buscador:/src

    web:
        build: ./web
        depends_on:
            - db
            - cache
        env_file: .env.local
        environment:
            - DJANGO_SETTINGS_MODULE=settings
        volumes:
            - web_uwsgispooler_dev:/var/uwsgispooler
            - web_uwsgilog_dev:/var/log/uwsgi/
            - web_static:/static
            - web_media:/media
            - ./web:/app:cached
        ports:
            - 8080:8000
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

    db:
        build: ./postgres
        env_file: .env.local
        volumes:
            - db_dev:/var/lib/postgresql/data
        #add this if you need to connect to psql from outside
        ports:
           - "5432:5432"

    # rtapi:
    #     build: ./rtapi
    #     ports:
    #         - 8084:8000
    #     volumes:
    #         - ./rtapi:/app
    #     depends_on:
    #         - redis
    #         - db
    #         - poller

    # poller:
    #     build: ./poller
    #     volumes:
    #         - ./poller:/app
    #     depends_on:
    #         - db
    #     env_file: .env.local

    cache:
        image: memcached:alpine

    # redis:
    #     image: redis

volumes:
    db_dev:
    api_uwsgispooler_dev:
    api_uwsgilog_dev:
    web_uwsgispooler_dev:
    web_uwsgilog_dev:
    web_static:
    web_media:
