version: '3.2'

services:

    api:
        build: ./api
        depends_on:
            - db
            - cache
        env_file: .env
        restart: always
        environment:
            VIRTUAL_PORT: 8000
            VIRTUAL_HOST: api.cualbondi.com.ar
            LETSENCRYPT_HOST: api.cualbondi.com.ar
            LETSENCRYPT_EMAIL: cualbondi@gmail.com
        volumes:
            - ./volume_api_uwsgispooler:/var/uwsgispooler
            - ./volume_api_uwsgilog:/var/log/uwsgi/

    apiv3:
        build:
            context: ./apiv3
            dockerfile: docker/production/Dockerfile
        depends_on:
            - db
            - cache
        restart: always
        environment:
            DJANGO_SETTINGS_MODULE: config.settings.production
            VIRTUAL_PORT: 8000
            VIRTUAL_HOST: api3.cualbondi.com.ar
            LETSENCRYPT_HOST: api3.cualbondi.com.ar
            LETSENCRYPT_EMAIL: cualbondi@cualbondi.com.ar
        env_file: .env
        volumes:
            - ./volume_apiv3_media:/media
        command: /gunicorn.sh

    web:
        build: ./web
        depends_on:
            - db
            - cache
        env_file: .env
        restart: always
        environment:
            VIRTUAL_PORT: 8000
            VIRTUAL_HOST: cualbondi.com.ar
            LETSENCRYPT_HOST: cualbondi.com.ar
            LETSENCRYPT_EMAIL: cualbondi@gmail.com
        volumes:
            - ./volume_web_uwsgispooler:/var/uwsgispooler
            - ./volume_web_uwsgilog:/var/log/uwsgi/
            - ./volume_web_static:/static
            - ./volume_web_media:/media

    db:
        build: ./postgres
        restart: always
        env_file: .env
        volumes:
            - ./volume_db:/var/lib/postgresql/data
        sysctls:
            - kernel.shmmax=4294967296
            - kernel.shmall=4194304
            #- vm.nr_hugepages=6000 # not namespaced must be set outside docker
        command: postgres -c shared_buffers=2GB -c work_mem=128MB -c statement_timeout=30000 -c max_parallel_workers_per_gather=4 -c max_worker_processes=16

    cache:
        image: memcached:alpine
        restart: always

    proxy:
        image: jwilder/nginx-proxy:alpine
        ports:
            - 80:80
            - 443:443
        restart: always
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
            - ./nginx/vhost.d:/etc/nginx/vhost.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./volume_nginx/logs:/var/log/nginx
            - ./volume_nginx/html:/usr/share/nginx/html
            - ./volume_nginx/certificates:/etc/nginx/certs
            - ./volume_web_static:/www/static
            - ./volume_web_media:/www/media
        labels:
            - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
        environment:
            DEFAULT_HOST: cualbondi.com.ar
        sysctls:
            - net.core.somaxconn=16384
            - net.ipv4.tcp_synack_retries=2
            - net.ipv4.tcp_syn_retries=2
            - net.ipv4.tcp_fin_timeout=10
            #- net.ipv4.tcp_slow_start_after_idle=0 # not found?
            #- net.ipv4.tcp_mem=524288 524288 524288 # not found?
            #- net.ipv4.tcp_max_tw_buckets=1048576 # not found?
            #- net.ipv4.tcp_max_syn_backlog=4096 # not found?
            - net.ipv4.tcp_tw_reuse=1
            - net.ipv4.tcp_keepalive_intvl=15
            - net.ipv4.tcp_keepalive_probes=5

    # https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion
    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: on-failure
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./volume_nginx/certificates:/etc/nginx/certs
            - ./volume_nginx/vhost.d:/etc/nginx/vhost.d
            - ./volume_nginx/html:/usr/share/nginx/html
        # environment:
        #     DEBUG: "true"





####### SENTRY ###########

    sentry_redis:
        image: redis

    sentry_postgres:
        image: postgres
        environment:
            POSTGRES_USER: sentry
            POSTGRES_PASSWORD: sentry
            POSTGRES_DBNAME: sentry
            POSTGRES_DBUSER: sentry
            POSTGRES_DBPASS: sentry
        volumes:
            - ./volume_sentry_postgres:/var/lib/postgresql/data

    sentry_sentry:
        image: sentry
        links:
            - sentry_redis
            - sentry_postgres
        environment:
            SENTRY_SECRET_KEY: '3KOZCsauzjLAs8B4HjkY'
            SENTRY_POSTGRES_HOST: sentry_postgres
            SENTRY_DB_USER: sentry
            SENTRY_DB_PASSWORD: sentry
            SENTRY_REDIS_HOST: sentry_redis
            LETSENCRYPT_HOST: sentry.cualbondi.com.ar
            LETSENCRYPT_EMAIL: cualbondi@cualbondi.com.ar
            VIRTUAL_HOST: sentry.cualbondi.com.ar
            VIRTUAL_PORT: 9000

    sentry_cron:
        image: sentry
        links:
            - sentry_redis
            - sentry_postgres
        command: "sentry run cron"
        environment:
            SENTRY_SECRET_KEY: '3KOZCsauzjLAs8B4HjkY'
            SENTRY_POSTGRES_HOST: sentry_postgres
            SENTRY_DB_USER: sentry
            SENTRY_DB_PASSWORD: sentry
            SENTRY_REDIS_HOST: sentry_redis

    sentry_worker:
        image: sentry
        links:
            - sentry_redis
            - sentry_postgres
        command: "sentry run worker"
        environment:
          SENTRY_SECRET_KEY: '3KOZCsauzjLAs8B4HjkY'
          SENTRY_POSTGRES_HOST: sentry_postgres
          SENTRY_DB_USER: sentry
          SENTRY_DB_PASSWORD: sentry
          SENTRY_REDIS_HOST: sentry_redis
