version: '3.2'

services:

    api:
        build: ./api
        depends_on:
            - db
            - cache
        env_file: .env
        restart: always
        environment:
            DB_HOST: db
            VIRTUAL_PORT: 8000
            VIRTUAL_HOST: api.cualbondi.com.ar
            LETSENCRYPT_HOST: api.cualbondi.com.ar
            LETSENCRYPT_EMAIL: cualbondi@cualbondi.com.ar
        volumes:
            - ./volume_api_uwsgispooler:/var/uwsgispooler
            - ./volume_api_uwsgilog:/var/log/uwsgi/

    web:
        build: ./web
        depends_on:
            - db
            - cache
        env_file: .env
        restart: always
        environment:
            DB_HOST: db
            VIRTUAL_PORT: 8000
            VIRTUAL_HOST: cualbondi.com.ar
            LETSENCRYPT_HOST: cualbondi.com.ar
            LETSENCRYPT_EMAIL: cualbondi@cualbondi.com.ar
        volumes:
            - ./volume_web_uwsgispooler:/var/uwsgispooler
            - ./volume_web_uwsgilog:/var/log/uwsgi/
            - ./volume_web_static:/static
            - ./volume_web_media:/media

    db:
        build: ./postgres
        restart: always
        env_file: .env
        ports:
            - "5432:5432"
        volumes:
            - ./volume_db:/var/lib/postgresql/data
        sysctls:
            - kernel.shmmax=4294967296
            - kernel.shmall=4194304
            #- vm.nr_hugepages=6000 # not namespaced must be set outside docker
        # command: postgres -c shared_buffers=2GB -c work_mem=128MB -c statement_timeout=30000 -c max_parallel_workers_per_gather=4 -c max_worker_processes=16

    cache:
        image: memcached:alpine
        restart: always

    proxy:
        image: jwilder/nginx-proxy:alpine
        ports:
            - 80:80
            - 443:443
        restart: always
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./volume_nginx/logs:/var/log/nginx
            - ./volume_nginx/html:/usr/share/nginx/html
            - ./volume_nginx/certificates:/etc/nginx/certs:ro
            - ./volume_web_static:/www/static
            - ./volume_web_media:/www/media
        labels:
            - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
        environment:
            DEFAULT_HOST: cualbondi.com.ar
        # sysctls:
            # - net.core.somaxconn=16384
            # - net.ipv4.tcp_synack_retries=2
            # - net.ipv4.tcp_syn_retries=2
            # - net.ipv4.tcp_fin_timeout=10
            #- net.ipv4.tcp_slow_start_after_idle=0 # not found?
            #- net.ipv4.tcp_mem=524288 524288 524288 # not found?
            #- net.ipv4.tcp_max_tw_buckets=1048576 # not found?
            #- net.ipv4.tcp_max_syn_backlog=4096 # not found?
            # - net.ipv4.tcp_tw_reuse=1
            # - net.ipv4.tcp_keepalive_intvl=15
            # - net.ipv4.tcp_keepalive_probes=5

    # https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion
    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: on-failure
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./volume_nginx/certificates:/etc/nginx/certs:rw
            - ./volume_nginx/vhost.d:/etc/nginx/vhost.d:rw
            - ./volume_nginx/html:/usr/share/nginx/html
