version: '3.2'

services:

    web-buscador:
        image: cypress/base:10
        ports:
            - 8083:8080
        command: bash -c "yarn && yarn serve"
        working_dir: /src
        volumes:
            - ./web-buscador:/src

    web:
        build:
            context: ./web
            dockerfile: docker/local/Dockerfile
        depends_on:
            - db
            - cache
        env_file: .env.local
        volumes:
            - ./web_static:/static
            - ./web_media:/media
            - ./web:/app:cached
        ports:
            - 8080:8000
        command: ["/start.sh"]


    db:
        build: ./postgres
        env_file: .env.local
        volumes:
            - db_dev:/var/lib/postgresql/data
        #add this if you need to connect to psql from outside
        ports:
           - "5432:5432"

    # rtapi:
    #     build: ./rtapi
    #     env_file: .env.local
    #     ports:
    #         - 8084:8000
    #     volumes:
    #         - ./rtapi/src:/app
    #     depends_on:
    #         - redis
    #         - db
    #         - poller
    #     command: ["python", "server.py"]

#    poller:
#        build: ./poller
#        volumes:
#            - ./poller:/go/src/app
#        depends_on:
#            - db
#            - redis
#        env_file: .env.local
#        command: tail -f /dev/null

    cache:
        image: memcached:alpine

    redis:
        image: redis

volumes:
    db_dev:
    api_uwsgispooler_dev:
    api_uwsgilog_dev:
    web_uwsgispooler_dev:
    web_uwsgilog_dev:
    web_static:
    web_media:
