version: '3.2'

services:

    api:
        build: ./api
        depends_on:
            - db
            - cache
        env_file: .env
        environment:
            - DB_HOST=db
            - VIRTUAL_HOST=api.cualbondi.local
            - VIRTUAL_PORT=8000
            - DEBUG=True
        volumes:
            - api_uwsgispooler_dev:/var/uwsgispooler
            - api_uwsgilog_dev:/var/log/uwsgi/

    web:
        build: ./web
        env_file: .env
        environment:
            - DB_HOST=db
            - DEBUG=True
            - VIRTUAL_HOST=cualbondi.local
            - VIRTUAL_PORT=8000
            - CUALBONDI_ENV=development
        volumes:
            - web_uwsgispooler_dev:/var/uwsgispooler
            - web_uwsgilog_dev:/var/log/uwsgi/
            - web_static:/static
            - web_media:/media

    db:
        build: ./postgres
        restart: unless-stopped
        env_file: .env
        volumes:
            - db_dev:/var/lib/postgresql/data

    cache:
        image: memcached:alpine
        restart: unless-stopped

    proxy:
        image: jwilder/nginx-proxy
        ports:
            - 80:80
            - 443:443
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nginx/proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
            - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
            - web_static:/www/static
            - web_media:/www/media
        environment:
            - DEFAULT_HOST=cualbondi.local
            - VIRTUAL_HOST=static.cualbondi.local,media.cualbondi.local

volumes:
    db_dev:
    api_uwsgispooler_dev:
    api_uwsgilog_dev:
    web_uwsgispooler_dev:
    web_uwsgilog_dev:
    web_static:
    web_media:
