version: '3.2'

services:

    apiv3:
        build:
            context: ./apiv3
            dockerfile: docker/local/Dockerfile
        depends_on:
            - db
            - cache
        env_file: .env.local
        volumes:
            - ./apiv3:/app:cached
        ports:
            - 8082:8000
        command: ["/start.sh"]

    web-buscador:
        build: ./web-buscador
        ports:
            - 8083:8080

    web:
        build: ./web
        depends_on:
            - db
            - cache
        env_file: .env.local
        environment:
            - DJANGO_SETTINGS_MODULE=settings
        volumes:
            - web_uwsgispooler_dev:/var/uwsgispooler
            - web_uwsgilog_dev:/var/log/uwsgi/
            - web_static:/static
            - web_media:/media
            - ./web:/app:cached
        ports:
            - 8080:8000
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

    db:
        build: ./postgres
        env_file: .env.local
        volumes:
            - db_dev:/var/lib/postgresql/data
        #add this if you need to connect to psql from outside
        ports:
           - "5432:5432"

    rtapi:
        build: ./rtapi
        env_file: .env.local
        ports:
            - 8084:8000
        volumes:
            - ./rtapi/src:/app
        depends_on:
            - redis
            - db
            - poller
        command: ["python", "server.py"]

    poller:
        build: ./poller
        volumes:
            - ./poller:/go/src/app
        depends_on:
            - db
        env_file: .env.local

    cache:
        image: memcached:alpine

    redis:
        image: redis

volumes:
    db_dev:
    api_uwsgispooler_dev:
    api_uwsgilog_dev:
    web_uwsgispooler_dev:
    web_uwsgilog_dev:
    web_static:
    web_media:
