version: '3.2'

services:

    api:
        build: ./api
        depends_on:
            - db
            - cache
        restart: unless-stopped
        env_file: .env.local
        environment:
            - MEMCACHED_HOST=cache
        volumes:
            - api_uwsgispooler_dev:/var/uwsgispooler
            - api_uwsgilog_dev:/var/log/uwsgi/
            - ./api:/app
        ports:
            - 8081:8000
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

    apiv3:
        build:
            context: ./apiv3
            dockerfile: docker/local/Dockerfile
        depends_on:
            - db
            - cache
        restart: unless-stopped
        env_file: .env.local
        volumes:
            - ./apiv3:/app
        ports:
            - 8082:8000
        command: /start.sh

    web:
        build: ./web
        depends_on:
            - db
            - cache
        restart: unless-stopped
        env_file: .env.local
        environment:
            - MEMCACHED_HOST=cache
            - API_URL=http://localhost:8081/
        volumes:
            - web_uwsgispooler_dev:/var/uwsgispooler
            - web_uwsgilog_dev:/var/log/uwsgi/
            - web_static:/static
            - web_media:/media
            - ./web:/app
        ports:
            - 8080:8000
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

    db:
        build: ./postgres
        restart: unless-stopped
        env_file: .env.local
        volumes:
            - db_dev:/var/lib/postgresql/data
        #add this if you need to connect to psql from outside
        ports:
           - "5432:5432"

    cache:
        image: memcached:alpine
        restart: unless-stopped


volumes:
    db_dev:
    api_uwsgispooler_dev:
    api_uwsgilog_dev:
    web_uwsgispooler_dev:
    web_uwsgilog_dev:
    web_static:
    web_media:
